spring:
  application:
    name: demo
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static: us-east-2
      stack:
        auto: false